### ISSUE TITLE
How to use it with Polish?

### ISSUE THREAD

**Issue by gitowiec** [NATSpeech/NATSpeech#5]
I would like it to speak Polish, how I can configure it to do it?
Thanks

**Comment by RayeRen** [comment]
1. Add a Polish text processor (g2p, text normalization ......) like`data_gen/tts/txt_processors/polish.py`
2. Add a config file in `datasets/audio/XXX_Dataset/ps_flow.yaml`, with the following content:
```yaml
base_config:
  - egs/egs_bases/tts/ps_flow.yaml
raw_data_dir: data/raw/XXXX
processed_data_dir: data/processed/XXX
binary_data_dir: data/binary/XXX
preprocess_args:
  txt_processor: polish # here is the text processor name registered in your text processor file.
```
3. Add the dataset metadata loader in `egs/datasets/audio/XXX_Dataset/preprocess.py`. You can refer to the metadata loader of LJSpeech (`egs/datasets/audio/lj/preprocess.py`).
4. Train the model with `python run.py --config YOUR_CONFIG ....` as the document `docs/portaspeech.md` says.
